config/routes.rb
Rails.application.routes.draw do
  resources :administrator do
    collection do
      get 'login'
      get 'logout'
    end
  end
  root :to => "articles#index"
  resources :articles do
  	resources :comments do

  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :subtitle, presence: true, length: { maximum: 250 }
  validates :body, presence: true
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :commenter, presence: true
  validates :body, presence: true
  belongs_to :article
end

app/controllers/administrator_controller.rb
class AdministratorController < ApplicationController

  # GET /administrator
  def index
    @articles = Article.all
  end
  
  def login
    session[:is_admin] = true
    @is_admin = true
    redirect_back(fallback_location: root_path)
  end

  def logout
    session[:is_admin] = false
    @is_admin = false
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_admin
  before_filter :set_cache_headers

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin
    	@is_admin = session[:is_admin]
    end

	def set_cache_headers
    response.headers["Surrogate-Control"] = "no-store"
    response.headers["Cache-Control"] = "no-store, no-cache, must-revalidate, proxy-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "0"
    response.headers["X-XSS-Protection"] = "1; mode=block"
    if response.headers["X-Powered-By"]
      response.headers.delete("X-Powered-By")
    end
    response.headers["X-DNS-Prefetch-Control"] = "off"
    response.headers["X-Frame-Options"] = "SAMEORIGIN"
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["X-Download-Options"] = "noopen"
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    if @is_admin
      @article = Article.new
    else
      redirect_to root_url
    end
  end

  # GET /articles/1/edit
  def edit
    if @is_admin
    else
      redirect_to root_url
    end
  end

  # POST /articles
  # POST /articles.json
  def create
    if @is_admin
      @article = Article.new(article_params)
  
      respond_to do |format|
        if @article.save
          format.html { redirect_to @article, notice: '' }
          format.json { render :show, status: :created, location: @article }
        else
          format.html { render :new }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_url
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    if @is_admin
      respond_to do |format|
        if @article.update(article_params)
          format.html { redirect_to :back, notice: '' }
          format.json { render :show, status: :ok, location: @article }
        else
          format.html { render :edit }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_url
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    if @is_admin
      @article.destroy
      respond_to do |format|
        format.html { redirect_to :back, notice: '' }
        format.json { head :no_content }
      end
    else
      redirect_to root_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :subtitle, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /articles/:article_id/comments/
  def index
    @comments = @article.comments;
  end

  # GET /articles/:article_id/comments/:id
  def show
  end

  # GET /articles/:article_id/comments/
  def new
    @article = @article.comments
  end

  # POST /articles/:article_id/comments/
  def create
    @comment = @article.comments.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to :back, notice: '' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { redirect_to article_path(@article) }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
    	@article = Article.find(params[:article_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = @article.comments.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/helpers/administrator_helper.rb
module AdministratorHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/administrator/index.html.erb
<style>
.demo-card > .mdl-card__title {
  color: #fff;
  background:
    bottom right 15% no-repeat #46B6AC;
}
.demo-card > .mdl-card__menu {
  color: #fff;
}
.demo-card > .mdl-card__title > h3 {
  margin: 0;
}
.demo-card > .mdl-card__title > h6 {
  margin: 0;
}
#view-source {
  position: fixed!important;
  display: block;
  right: 0;
  bottom: 0;
  margin-right: 40px;
  margin-bottom: 40px;
  z-index: 900;
  -webkit-transition: all 300ms;
  -moz-transition: all 300ms;
  -ms-transition: all 300ms;
  -o-transition: all 300ms;
  transition: all 300ms;
}
.demo-mdl-button--fab {
  position: fixed!important;
    bottom: 24px;
    right: 40px;
  -webkit-transition: all 300ms;
  -moz-transition: all 300ms;
  -ms-transition: all 300ms;
  -o-transition: all 300ms;
  transition: all 300ms;
  transform: scale(0);
}
</style>
<p id="notice"><%= notice %></p>
  <table class="mdl-cell mdl-cell--12-col mdl-data-table mdl-js-data-table mdl-shadow--4dp">
    <thead>
      <tr>
        <th class="mdl-data-table__cell--non-numeric">Titulo</th>
        <th class="mdl-data-table__cell--non-numeric mdl-data-table__header--sorted-descending">Fecha</th>
        <th class="mdl-data-table__cell--non-numeric"></th>
        <th class="mdl-data-table__cell--non-numeric"></th>
      </tr>
    </thead>
    <tbody>
      <% @articles.order('created_at DESC').each do |article| %>
        <tr>
          <td class="mdl-data-table__cell--non-numeric">
            <% title = article.title %>
            <% if title.length >= 100 %>
            <%= title[0, 97] << '...' %>
            <% else %>
            <%= title %>
            <% end %>
            </td>
          <td class="mdl-data-table__cell--non-numeric"><%= article.created_at.to_time.strftime('%B %e at %l:%M %p') %> </td>
          <td>
            <%= link_to 'Editar', edit_article_path(article), :class=> "mdl-button mdl-button--colored  mdl-js-button mdl-js-ripple-effect" %>
          </td>
          <td>
              <%= link_to 'Borrar', article, method: :delete, data: { confirm: '¿Estás segur@?' }, :class => "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

<a href=<%= new_article_path %> id="view-source" class="mdl-button mdl-js-button mdl-button--fab mdl-button--colored"><i class="material-icons">add</i></a>

app/views/articles/_form.html.erb
<style>
  .demo-container {
    max-width: 1600px;
    width: calc(100% - 16px);
    margin: 0 auto;
  }
  .demo-content {
    border-radius: 2px;
    padding: 80px 56px;
    margin-bottom: 80px;
  }
</style>

<div class="demo-container mdl-grid">
  <div class="mdl-cell mdl-cell--2-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>
  <div class="demo-content mdl-color--white mdl-shadow--4dp content mdl-color-text--grey-800 mdl-cell mdl-cell--8-col">
  <%= form_for(article) do |f| %>
    <% if article.errors.any? %>
      <div id="error_explanation">
        <h3><%= pluralize(article.errors.count, "error") %> prohibited this article from being  saved:</h3>

        <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field mdl-textfield mdl-js-textfield">
      <input <% if article.title? %> value=<%=article.title%> <% end %> class=" mdl-textfield__input" name="article[title]" type="text" id="article_title">
      <label class="mdl-textfield__label" for="article_title">Titulo</label>
    </div>
    <br>
  
    <div class="field mdl-textfield mdl-js-textfield">
      <input  <% if article.subtitle? %> value=<%=article.subtitle%> <% end %> class="  mdl-textfield__input" name="article[subtitle]" type="text" id="article_subtitle">
      <label class="mdl-textfield__label" for="article_subtitle">Bajada</label>
    </div>
    <br>
  
    <div class="field mdl-textfield mdl-js-textfield">
      <textarea class="mdl-textfield__input" type="text" name="article[body]" rows= "3" id="  article_body" ><% if article.body? %><%=article.body%><% end %></textarea>
      <label class="mdl-textfield__label" for="article_body">Cuerpo</label>
    </div>
    <br>
  
    <div class="actions">
      <%= f.submit "Submit", :class => "mdl-button mdl-js-button mdl-button--raised   mdl-button--colored" %>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<style>
.demo-blog .demo-blog__posts > .demo-nav > .demo-nav__button:first-child .mdl-button {
  margin-right: 16px;
}
.demo-blog .demo-blog__posts > .demo-nav > .demo-nav__button:last-child .mdl-button {
  margin-left: 16px;
}
</style>
<%= render 'form', article: @article %>
<a href=<%= articles_path %> title="Volver">
  <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
    <i class="material-icons" role="presentation">arrow_backward</i>
  </button>
</a>
<a href=<%= article_path(@article) %> title="Mostrar">
  <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
    <i class="material-icons" role="presentation">launch</i>
  </button>
</a>

app/views/articles/index.html.erb
<style>
  .demo-card > .mdl-card__title {
    color: #fff;
    background:
      bottom right 15% no-repeat #00bbbb;
  }
  .demo-card > .mdl-card__menu {
    color: #fff;
  }
  .demo-card > .mdl-card__title > h3 {
    margin: 0;
  }
  .demo-card > .mdl-card__title > h6 {
    margin: 0;
  }
  #view-source {
    position: fixed;
    display: block;
    right: 0;
    bottom: 0;
    margin-right: 40px;
    margin-bottom: 40px;
    z-index: 900;
  }
  .portfolio-max-width {
    max-width: 900px;
    margin: auto;
  }

  .portfolio-card .mdl-card__title {
    padding-bottom: 0;
  }

  .no-bottom-padding {
    padding-bottom: 0;
  }

  .portfolio-btn {
  position: relative;
  float: right;
  top: -4px;
}

</style>
<% if @is_admin %>
  <a href=<%= new_article_path %> id="view-source" class="mdl-button mdl-js-button mdl-button--fab mdl-button--colored"><i class="material-icons">add</i></a>
<% end %>
<p id="notice"><%= notice %></p>
<div class="mdl-grid portfolio-max-width">
  <% @articles.order('created_at DESC').each do |article| %>
    <div class="mdl-cell mdl-cell--6-col demo-card mdl-card mdl-shadow--4dp">
      <div class="mdl-card__title mdl-card--expand">
        <h3><%= article.title %></h3>
      </div>
      <div class="mdl-card__media">
      </div>
      <div class="mdl-card__title mdl-card--expand">
        <span> <%= article.subtitle[0, 250] %> </span>
      </div>
      <div class="mdl-card__supporting-text">
        <p>
          <% body = article.body %>
          <% if body.length >= 1000 %>
            <%= body[0, 997] << '...' %>
          <% else %>
            <%= body %>
          <% end %>
        </p>
      </div>
      <div class="mdl-card__actions mdl-card--border" style="text-align: center;">
        <%= link_to 'Ver', article, :class=> "mdl-button mdl-button--colored mdl-js-button  mdl-js-ripple-effect" %>
        <% if @is_admin %>
          <%= link_to 'Editar', edit_article_path(article), :class=> "mdl-button mdl-button--colored  mdl-js-button mdl-js-ripple-effect" %>
          <%= link_to 'Borrar', article, method: :delete, data: { confirm: '¿Estás segur@?' }, :class => "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>
        <% end %>
      </div>
      <div class="mdl-card__menu">
        <div class="material-icons mdl-badge mdl-badge--overlap" data-badge=<%= article.comments.size %>>comment</div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<%= render 'form', article: @article %>

<a href=<%= articles_path %> title="Volver">
  <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
    <i class="material-icons" role="presentation">arrow_backward</i>
  </button>
</a>

app/views/articles/show.html.erb
<style>
  .demo-container {
    max-width: 1600px;
    width: calc(100% - 16px);
    margin: 0 auto;
  }
  .demo-content {
    border-radius: 2px;
    padding: 80px 56px;
    margin-bottom: 80px;
  }
</style>
<div class="demo-container mdl-grid">
  <div class="mdl-cell mdl-cell--2-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>
  <div class="demo-content mdl-color--white mdl-shadow--4dp content mdl-color-text--grey-800 mdl-cell mdl-cell--8-col">
  <h3><%= @article.title %></h3>
  <h5 class="demo-crumbs mdl-color-text--grey-500">
    <%= @article.subtitle %>
  </h5>
  <br>
  <% @article.body.split("\t").each do |str| %>
    <p><%= str %></p>
  <% end %>
  <% if @article.comments.length > 0 %>
    <h4>Comentarios</h4>
    <ul class="mdl-list">
      <% @article.comments.each do |comment| %>
        <li class="mdl-list__item mdl-list__item--three-line">
          <span class="mdl-list__item-primary-content">
            <i class="material-icons mdl-list__item-avatar">person</i>
            <span><%= comment.commenter %></span>
            <span class="mdl-list__item-text-body">
              <%= comment.body %>
            </span>
          </span>
        </li>
      <% end %>
    </ul>
  <% end %>
  <h4>Nuevo comentario</h4>
  <%= render 'comments/form' %>
</div>

<a href=<%= articles_path %> title="Volver">
  <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
    <i class="material-icons" role="presentation">arrow_backward</i>
  </button>
</a>

<% if @is_admin %>
  <a href=<%= edit_article_path(@article) %> title="Editar">
    <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
      <i class="material-icons" role="presentation">edit</i>
    </button>
  </a>

<% end %>

<p id="notice"><%= notice %></p>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <div class="mdl-textfield mdl-js-textfield">
    <input class="mdl-textfield__input" name="comment[commenter]" type="text" id="comment_commenter">
    <label class="mdl-textfield__label" for="comment_commenter">Nombre</label>
  </div>
  <br>
  <div class="mdl-textfield mdl-js-textfield">
    <textarea class="mdl-textfield__input" type="text" name="comment[body]" rows= "3" id="comment_body" ></textarea>
    <label class="mdl-textfield__label" for="comment_body">Escribe aquí</label>
  </div>
  <p>
    <%= f.submit "Submit", :class => "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
  </p>
<% end %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Commenter</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.commenter %></td>
        <td><%= comment.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/comments/new.html.erb
<%= render 'form', comment: @comment %>

app/views/comments/show.html.erb
<p>
  <strong>Commenter:</strong>
  <%= @comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= @comment.body %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Noticias en vivo</title>
    <link rel="preload" href="https://fonts.googleapis.com/icon?family=Material+Icons" as="style" onload="this.rel='stylesheet'">
    <link rel="preload" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css" as="style" onload="this.rel='stylesheet'">
    <noscript>
      <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
      <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    </noscript>
    <script type="text/javascript">
      /*! loadCSS. [c]2017 Filament Group, Inc. MIT License */
    !function(a){"use strict";var b=function(b,c,d){function e(a){return h.body?a():void setTimeout(function(){e(a)})}function f(){i.addEventListener&&i.removeEventListener("load",f),i.media=d||"all"}var g,h=a.document,i=h.createElement("link");if(c)g=c;else{var j=(h.body||h.getElementsByTagName("head")[0]).childNodes;g=j[j.length-1]}var k=h.styleSheets;i.rel="stylesheet",i.href=b,i.media="only x",e(function(){g.parentNode.insertBefore(i,c?g:g.nextSibling)});var l=function(a){for(var b=i.href,c=k.length;c--;)if(k[c].href===b)return a();setTimeout(function(){l(a)})};return i.addEventListener&&i.addEventListener("load",f),i.onloadcssdefined=l,l(f),i};"undefined"!=typeof exports?exports.loadCSS=b:a.loadCSS=b}("undefined"!=typeof global?global:this);
    /*! loadCSS rel=preload polyfill. [c]2017 Filament Group, Inc. MIT License */
    !function(a){if(a.loadCSS){var b=loadCSS.relpreload={};if(b.support=function(){try{return a.document.createElement("link").relList.supports("preload")}catch(b){return!1}},b.poly=function(){for(var b=a.document.getElementsByTagName("link"),c=0;c<b.length;c++){var d=b[c];"preload"===d.rel&&"style"===d.getAttribute("as")&&(a.loadCSS(d.href,d,d.getAttribute("media")),d.rel=null)}},!b.support()){b.poly();var c=a.setInterval(b.poly,300);a.addEventListener&&a.addEventListener("load",function(){b.poly(),a.clearInterval(c)}),a.attachEvent&&a.attachEvent("onload",function(){a.clearInterval(c)})}}}(this);
    </script>
    <script async defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', async: true, defer: true %>
  </head>

  <body onload="setInterval(function() { window.componentHandler.upgradeDom(); }, 250);">
    <div class="mdl-layout mdl-js-layout">
      <header class="mdl-layout__header mdl-layout__header--scroll">
        <div class="mdl-layout__header-row mdl-layout--large-screen-only">
          <!-- Title -->
          <span class="mdl-layout-title">Noticias en vivo</span>
          <!-- Add spacer, to align navigation to the right -->
          <div class="mdl-layout-spacer"></div>
          <!-- Navigation -->
          <nav class="mdl-navigation">
            <% if @is_admin %>
              <%= link_to 'Inicio', root_path, :class => "mdl-navigation__link" %>
              <%= link_to 'Modo Administrador', administrator_index_path, :class => "mdl-navigation__link"%>
              <%= link_to 'Desconectar', logout_administrator_index_path, :class => "mdl-navigation__link"%>
            <% else %>
              <%= link_to 'Administrar', login_administrator_index_path, :class => "mdl-navigation__link"%>
            <% end %>
          </nav>
        </div>
      </header>
      <div class="mdl-layout__drawer mdl-layout--small-screen-only">
        <span class="mdl-layout-title">Noticias en vivo</span>
        <nav class="mdl-navigation">
          <% if @is_admin %>
            <%= link_to 'Inicio', root_path, :class => "mdl-navigation__link" %>
            <%= link_to 'Modo Administrador', administrator_index_path, :class => "mdl-navigation__link"%>
            <%= link_to 'Desconectar', logout_administrator_index_path, :class => "mdl-navigation__link"%>
          <% else %>
            <%= link_to 'Administrar', login_administrator_index_path, :class => "mdl-navigation__link"%>
          <% end %>
        </nav>
      </div>
      <main class="mdl-layout__content">
        <div class="page-content">
          <%= yield %>
        </div>
      </main>
    </div>
    
  </body>
</html>